### ISSUE TITLE
User profile page

### ISSUE THREAD

**Issue by ehakan** [itucsdb1817/itucsdb1817#20]
Should include:
- [x] Posts submitted 9f3c5c98f8062441d90f21b2e267bc6069e4c211
- [x] Password change 27d196feab874cfc8f6eed7ef24fd0c94d08396e
- [x] Comments
- [x] Votes

**Comment by busekuz** [comment]
Missing parts are,
- User's reports are public
- Votes does not show the content of post / comment but only the type, date and submitted_id
